project_id = "fmdceepatwdfkmozgkcq"

[functions.setup-admin]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
